apiVersion: apps/v1
kind: Deployment
metadata:
  name: trending-deployment
  namespace: pythonapp-namespace
spec:
  replicas: 0  # Rollout will manage replicas
  selector:
    matchLabels:
      app: trending
  template:
    metadata:
      labels:
        app: trending
    spec:
      containers:
      - name: trending
        image: devopsuses/mytrending-service:v7
        ports:
        - containerPort: 5001
        resources:
          requests:
            memory: 128Mi
            cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  name: trending-service
  namespace: pythonapp-namespace
spec:
  ports:
  - port: 5001
    targetPort: 5001
    protocol: TCP
    name: http
  selector:
    app: trending
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: trending-destrule
  namespace: pythonapp-namespace
spec:
  host: trending-service
  subsets:
  - name: canary
    labels:
      app: trending
  - name: stable
    labels:
      app: trending
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: trending-virtualservice
  namespace: pythonapp-namespace
spec:
  gateways:
  - istio-system/pythonapp-gateway
  hosts:
  - "*"
  http:
  - name: trending-route
    route:
    - destination:
        host: trending-service
        port:
          number: 80
        subset: stable
      weight: 100
    - destination:
        host: trending-service
        port:
          number: 80
        subset: canary
      weight: 0
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: trending-rollout
  namespace: pythonapp-namespace
spec:
  replicas: 1
  strategy:
    canary:
      trafficRouting:
        istio:
          virtualService:
            name: trending-virtualservice
            routes:
            - trending-route
          destinationRule:
            name: trending-destrule
            canarySubsetName: canary
            stableSubsetName: stable
      steps:
      - setWeight: 20
      - pause: {duration: 10s}
      - setWeight: 50
      - pause: {duration: 10s}
      - setWeight: 100
      - pause: {}
  selector:
    matchLabels:
      app: trending
  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: trending-deployment
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-trending
  namespace: pythonapp-namespace
spec:
  maxReplicas: 5
  minReplicas: 2
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: trending-rollout
  targetCPUUtilizationPercentage: 50

